### ISSUE TITLE
Update to version 2.0.0

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/heroicons#141]
### Description

Version 2.0.0 of the icons was just released upstream: https://twitter.com/steveschoger/status/1562117153591107586 , https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0

Time to update them here!

There are now three sets to support: outline, solid, and mini.

**Comment by lcfd** [comment]
I hope it will happen soon because the situation starts to get confusing when I look for the icons on the HeroIcons site 😂

**Comment by adamchainz** [comment]
There’s an open PR: #143

If you could help test it with a [VCS install](https://pip.pypa.io/en/stable/topics/vcs-support/) that would be useful. I want to try it out on a project before I merge it.

I also had the idea to provide a tool to update template tags from the old icon names to the new ones, to ease migration.

**Comment by lcfd** [comment]
> [VCS install](https://pip.pypa.io/en/stable/topics/vcs-support/)

I'm not familiar with this tool, can I do the same thing if I'm using Poetry?

> I also had the idea to provide a tool to update template tags from the old icon names to the new ones, to ease migration.

That would be awesome!

**Comment by adamchainz** [comment]
"this tool" = pip 😂

Yes read the poetry docs

**Comment by lcfd** [comment]
🤣  I meant VCS Support itself, not pip.
Let's see if I can do something!
