### ISSUE TITLE
can i assign attribute d to the path?

### ISSUE THREAD

**Issue by simkimsia** [adamchainz/heroicons#154]
### Description

```
<svg class="flex-shrink-0 w-6 h-6 text-teal-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
   <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
</svg>
```

This is what i want to replace with heroicons, but when I do this
```
{% heroicon_outline "check" stroke_width="2" stroke="currentColor" aria_hidden="true" d="M5 13l4 4L19 7" size=24 class="flex-shrink-0 w-6 h-6 text-teal-500"  %}
```

I get 

```
<svg fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true" width="24" height="24" d="M5 13l4 4L19 7" class="flex-shrink-0 w-6 h-6 text-teal-500">
  <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5"></path>
</svg>
```

as you can see, the d inside path is different. Not sure why. How do I override it?

**Comment by adamchainz** [comment]
The first icon you pasted is from heroicons v1. The result you're seeing is the v2 icon.

Version 2.0.0 of this package moved to the v2 icon set: https://github.com/adamchainz/heroicons/blob/main/HISTORY.rst

If you want v1 icons, install version 1.8.0.

**Comment by simkimsia** [comment]
Oh i'm sorry i didn't realize the different d values was for an older heroicons. Apologies 🙇🏻‍♂️
