### ISSUE TITLE
Add support for use in Wagtail admin

### ISSUE THREAD

**Issue by joshuadavidthomas** [adamchainz/heroicons#158]
I recently created an open-source package ([wagtail-heroicons](https://github.com/joshuadavidthomas/wagtail-heroicons)) to add the ability to use Heroicons throughout the [Wagtail CMS](https://wagtail.org/) admin, extracted from what I was doing on a private repository for my day job.

While my package does what it needs to do for me, it is a bit limiting as you can only use the icons within the admin interface, not in any templates written for Wagtail pages. I have thought about adding that ability as I think it adds to the usefulness for the community but seeing as this package already exists and is **much** better written than my own, I wanted to see if there was interest in adding support for the Wagtail admin within this package.

Thanks!

**Comment by adamchainz** [comment]
I’m not interested in adding any Wagtail-specific features. I don’t use Wagtail so I won’t be able to maintain such features.

But I’d be happy to add any necessary hooks for your package. After a quick skim through the source, it seems you might need a function to list all the icons?

**Comment by joshuadavidthomas** [comment]
Sorry for the delay in responding! Thanks so much for taking the time to consider this issue, and I totally understand why you would not be interested in taking on the burden of supporting something you yourself don't use.

I've been knee-deep in a new project at work and will need to think through what all my package could/would need from yours. When I figure that out I will open another issue with the more specific request. 

Thanks!

**Comment by adamchainz** [comment]
Okay thanks for letting me know!
