### ISSUE TITLE
Heroicons 2.1

### ISSUE THREAD

**Issue by jefftriplett** [adamchainz/heroicons#251]
### Description

A new version of Heroicons (2.1.1) just dropped, which supports a new "Micro" size. 

Passing this along in case you haven't seen it yet. 

Blog post announcement: https://tailwindcss.com/blog/heroicons-micro 

Changelog: https://github.com/tailwindlabs/heroicons/blob/master/CHANGELOG.md

**Comment by adamchainz** [comment]
Thanks, working on it.

**Comment by jefftriplett** [comment]
@adamchainz zero rush. Just noting it because I was happy/surprised to see a new release in what was a busy week. 

Thanks again for maintaining this and all the things!

**Comment by adamchainz** [comment]
Released in 2.6.0.
